# Generated by Django 5.1 on 2024-09-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liability', '0002_rename_amount_liability_balance_liability_balance_bf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liability',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='liability',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
