# Generated by Django 5.1 on 2024-10-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liability', '0004_liabilitypayment_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liabilitypayment',
            options={'ordering': ['-payment_date', '-created_at']},
        ),
    ]
