# Generated by Django 5.1.2 on 2024-10-17 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liability', '0006_alter_liability_balance_bf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liabilitypayment',
            options={'ordering': ['payment_date', 'created_at']},
        ),
    ]
