# Generated by Django 5.1.2 on 2024-11-30 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_monthstatus'),
        ('liability', '0008_liabilitypayment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liabilitypayment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liability_payments', to='administration.transaction'),
        ),
    ]
