# Generated by Django 5.1.2 on 2025-01-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liability', '0009_alter_liabilitypayment_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liability',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='liability',
            unique_together={('name', 'year')},
        ),
    ]
