# Generated by Django 5.1.2 on 2025-04-29 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0017_alter_office_bank"),
        ("liability", "0011_alter_liabilitypayment_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="liability",
            name="office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liabilities",
                to="administration.office",
            ),
        ),
    ]
