# Generated by Django 5.1.2 on 2025-05-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liability", "0012_liability_office"),
    ]

    operations = [
        migrations.AddField(
            model_name="liability",
            name="seller",
            field=models.BooleanField(
                default=False, help_text="Indicates if the liability is a seller"
            ),
        ),
    ]
