# Generated by Django 5.1.2 on 2025-04-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_attendance"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("user", "date")},
        ),
    ]
