# Generated by Django 5.1.2 on 2025-04-29 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0016_office"),
        ("user", "0004_alter_attendance_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="administration.office",
            ),
        ),
    ]
