# Generated by Django 5.1.2 on 2024-11-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_date_alter_client_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(default='TEMP', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('WL', 'Weekly Loan'), ('ML', 'Monthly Loan'), ('DC', 'Daily Contribution')], default='WL', max_length=2),
        ),
    ]
