# Generated by Django 5.1.2 on 2025-02-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0008_alter_client_client_id_alter_client_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
