# Generated by Django 5.1.2 on 2025-02-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0009_client_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="image_url",
        ),
    ]
