# Generated by Django 5.1.2 on 2025-02-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0010_remove_client_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="account_status",
            field=models.CharField(
                choices=[("A", "Active"), ("L", "Lapse"), ("D", "Dormant")],
                default="A",
                max_length=1,
            ),
        ),
    ]
