# Generated by Django 5.1.2 on 2025-04-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0011_client_account_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("A", "Active"),
                    ("L", "Lapse"),
                    ("D", "Dormant"),
                    ("P", "Prospect"),
                ],
                default="A",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
