# Generated by Django 5.1.2 on 2025-04-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0013_alter_client_client_type_prospect"),
    ]

    operations = [
        migrations.AddField(
            model_name="prospect",
            name="is_activated",
            field=models.BooleanField(default=False),
        ),
    ]
