# Generated by Django 5.1.2 on 2025-04-09 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0014_prospect_is_activated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prospect",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prospect",
                to="client.client",
            ),
        ),
    ]
