# Generated by Django 5.1 on 2024-09-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_bank_balance_alter_bank_balance_bf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankpayment',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='bank',
            name='year',
            field=models.IntegerField(),
        ),
    ]
