# Generated by Django 5.1 on 2024-10-01 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_rename_bank_balance_bankpayment_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankpayment',
            old_name='balance',
            new_name='bank_balance',
        ),
    ]
