# Generated by Django 5.1 on 2024-10-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_rename_balance_bankpayment_bank_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankpayment',
            options={'ordering': ['payment_date', '-created_at']},
        ),
    ]
