# Generated by Django 5.1.2 on 2024-10-17 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_alter_bankpayment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='bankpayment',
            options={'ordering': ['payment_date', 'created_at']},
        ),
    ]
