# Generated by Django 5.1.2 on 2024-11-19 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_bankpayment_created_by_bankpayment_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpayment',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bank.bank'),
        ),
    ]
