# Generated by Django 5.1.2 on 2024-11-24 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_monthstatus'),
        ('bank', '0010_alter_bankpayment_bank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bankpayment',
            index=models.Index(fields=['payment_date'], name='idx_payment_date'),
        ),
        migrations.AddIndex(
            model_name='bankpayment',
            index=models.Index(fields=['payment_date', 'created_at'], name='idx_payment_date_created_at'),
        ),
        migrations.AddIndex(
            model_name='bankpayment',
            index=models.Index(fields=['created_by'], name='idx_created_by'),
        ),
    ]
