# Generated by Django 5.1.2 on 2024-11-30 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_monthstatus'),
        ('bank', '0012_alter_bankpayment_transaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bankpayment',
            name='idx_bank_payment_date',
        ),
        migrations.AddIndex(
            model_name='bankpayment',
            index=models.Index(fields=['bank', 'payment_date', 'transaction'], name='idx_bank_payment_transaction'),
        ),
    ]
