# Generated by Django 5.1.2 on 2025-04-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0015_pendingcashtransfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="type",
            field=models.CharField(
                choices=[("B", "Bank"), ("A", "Asset")], default="B", max_length=50
            ),
        ),
    ]
