# Generated by Django 5.1 on 2024-09-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomepayment',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='income',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='balance_bf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
