# Generated by Django 5.1 on 2024-09-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_remove_incomepayment_created_by_alter_income_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomepayment',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
