# Generated by Django 5.1.2 on 2025-01-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0006_alter_incomepayment_transaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='income',
            unique_together={('name', 'year')},
        ),
    ]
