# Generated by Django 5.1 on 2024-09-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_savingspayment_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompulsorySavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
