# Generated by Django 5.1 on 2024-09-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_compulsorysavings'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingspayment',
            name='description',
            field=models.TextField(default='Savings for None'),
        ),
    ]
