# Generated by Django 5.1 on 2024-09-16 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_savingspayment_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingspayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savingspayment',
            name='description',
            field=models.TextField(default='Savings for <django.db.models.fields.related.ForeignKey>'),
        ),
        migrations.AlterField(
            model_name='savingspayment',
            name='savings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='savings.savings'),
        ),
    ]
