# Generated by Django 5.1 on 2024-09-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_alter_savingspayment_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingspayment',
            name='created_by',
        ),
    ]
