# Generated by Django 5.1 on 2024-10-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_remove_savingspayment_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingspayment',
            options={'ordering': ['-payment_date', '-created_at']},
        ),
    ]
