# Generated by Django 5.1 on 2024-10-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0007_alter_savingspayment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingspayment',
            name='description',
            field=models.TextField(default='Savings for None'),
        ),
    ]
