# Generated by Django 5.1.2 on 2024-10-22 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_approval_type'),
        ('bank', '0009_bankpayment_created_by_bankpayment_transaction'),
        ('savings', '0010_savingspayment_created_by_savingspayment_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingspayment',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.approval'),
        ),
        migrations.AddField(
            model_name='savingspayment',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.bank'),
        ),
        migrations.AlterField(
            model_name='savingspayment',
            name='description',
            field=models.TextField(),
        ),
    ]
