# Generated by Django 5.1.2 on 2024-10-26 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_date_alter_client_created_at'),
        ('savings', '0012_remove_savingspayment_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='type',
            field=models.CharField(choices=[('N', 'Normal Savings'), ('D', 'Daily Contribution')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='savingspayment',
            name='transaction_type',
            field=models.CharField(choices=[('S', 'Savings'), ('W', 'Withdrawal'), ('C', 'Daily Contribution')], default='S', max_length=1),
        ),
        migrations.CreateModel(
            name='ClientContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='DailyContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_made', models.BooleanField(default=False)),
                ('client_contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.clientcontribution')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('client_contribution', 'date')},
            },
        ),
    ]
