# Generated by Django 5.1.2 on 2024-11-09 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0014_alter_savings_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycontribution',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='savings.savingspayment'),
        ),
    ]
