# Generated by Django 5.1.2 on 2024-11-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0015_dailycontribution_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='type',
            field=models.CharField(choices=[('N', 'Normal Savings'), ('D', 'Daily Contribution')], db_index=True, default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='savingspayment',
            name='payment_date',
            field=models.DateField(db_index=True),
        ),
    ]
