# Generated by Django 5.1.2 on 2025-01-30 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_alter_tickets_repayment_schedule'),
        ('savings', '0017_alter_savingspayment_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingspayment',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_payments', to='administration.transaction'),
        ),
    ]
