# Generated by Django 5.1.2 on 2025-02-02 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0018_alter_savingspayment_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycontribution',
            name='client_contribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_contributions', to='savings.clientcontribution'),
        ),
    ]
