# Generated by Django 5.1.2 on 2025-04-02 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0015_alter_approval_type"),
        ("savings", "0019_alter_dailycontribution_client_contribution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingspayment",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="savings_payments",
                to="administration.transaction",
            ),
        ),
    ]
