# Generated by Django 5.1 on 2024-09-25 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_remove_loanpayment_emi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='loan.loan'),
        ),
        migrations.AlterField(
            model_name='loanrepaymentschedule',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='loan.loan'),
        ),
    ]
