# Generated by Django 5.1 on 2024-10-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_alter_loanpayment_amount_alter_loanpayment_loan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanpayment',
            options={'ordering': ['-payment_date', '-created_at']},
        ),
    ]
