# Generated by Django 5.1 on 2024-10-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_created_at'),
        ('loan', '0005_alter_loanpayment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='payment_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='loanrepaymentschedule',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='loanrepaymentschedule',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='loanrepaymentschedule',
            name='payment_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['client', 'loan_type'], name='loan_loan_client__1db0ff_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['start_date', 'end_date'], name='loan_loan_start_d_b382d7_idx'),
        ),
        migrations.AddIndex(
            model_name='loanpayment',
            index=models.Index(fields=['client', 'loan'], name='loan_loanpa_client__7c2158_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepaymentschedule',
            index=models.Index(fields=['loan', 'due_date'], name='loan_loanre_loan_id_8fb045_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepaymentschedule',
            index=models.Index(fields=['loan', 'is_paid'], name='loan_loanre_loan_id_b65347_idx'),
        ),
    ]
