# Generated by Django 5.1.2 on 2024-10-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_alter_loan_created_at_alter_loan_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='emi',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='risk_premium',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
