# Generated by Django 5.1.2 on 2024-10-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_alter_loan_emi_alter_loan_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
