# Generated by Django 5.1.2 on 2024-11-26 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_loan_created_by_loan_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='payment_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.loanrepaymentschedule'),
        ),
    ]
