# Generated by Django 5.1.2 on 2024-12-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0014_alter_loan_transaction_alter_loanpayment_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-start_date']},
        ),
    ]
