# Generated by Django 5.1.2 on 2025-01-30 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_alter_tickets_repayment_schedule'),
        ('loan', '0015_alter_loan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='administration.transaction'),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_payments', to='administration.transaction'),
        ),
    ]
