# Generated by Django 5.1.2 on 2025-04-17 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0015_alter_prospect_client"),
        ("loan", "0018_alter_loan_transaction_alter_loanpayment_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="client.client",
            ),
        ),
    ]
