# Generated by Django 5.1.2 on 2025-05-12 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0018_alter_office_bank"),
        ("asset", "0003_asset_office"),
        ("liability", "0012_liability_office"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "depreciation_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual depreciation rate as a percentage",
                        max_digits=5,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Category",
                "verbose_name_plural": "Asset Categories",
            },
        ),
        migrations.RemoveField(
            model_name="assetrecord",
            name="asset",
        ),
        migrations.AlterModelOptions(
            name="assetrecord",
            options={
                "ordering": ["-created"],
                "verbose_name": "Asset Record",
                "verbose_name_plural": "Asset Records",
            },
        ),
        migrations.AddField(
            model_name="assetrecord",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assetrecord",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("Addition", "Addition"),
                    ("Removal", "Removal"),
                    ("Sale", "Sale"),
                ],
                default="Addition",
                help_text="Type of transaction (addition, removal, sale)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="assetrecord",
            name="quantity",
            field=models.IntegerField(
                help_text="Positive for additions, negative for consumption"
            ),
        ),
        migrations.CreateModel(
            name="AssetDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("stock", "Stock Item"),
                            ("ledger", "Cost of Sales Ledger Item"),
                            ("fixed", "Fixed Asset"),
                        ],
                        default="stock",
                        help_text="Determines behavior and related attributes",
                        max_length=10,
                    ),
                ),
                (
                    "default_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Default unit cost or sale price",
                        max_digits=10,
                    ),
                ),
                (
                    "default_useful_life_years",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Default useful life for fixed assets",
                        null=True,
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_definitions",
                        to="administration.office",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Definition",
                "verbose_name_plural": "Asset Definitions",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="assetrecord",
            name="definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="asset.assetdefinition",
            ),
        ),
        migrations.CreateModel(
            name="AssetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "capitalization_date",
                    models.DateField(help_text="Date when the asset was capitalized"),
                ),
                (
                    "depreciation_start",
                    models.DateField(
                        help_text="When depreciation begins; defaults to capitalization date"
                    ),
                ),
                (
                    "useful_life_years",
                    models.PositiveIntegerField(
                        default=0, help_text="Can override the default useful life"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_service", "In Service"),
                            ("disposed", "Disposed"),
                            ("under_repair", "Under Repair"),
                        ],
                        default="in_service",
                        max_length=20,
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="asset.assetdefinition",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="liability.liability",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Item",
                "verbose_name_plural": "Asset Items",
            },
        ),
        migrations.AddField(
            model_name="assetrecord",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="asset.assetitem",
            ),
        ),
        migrations.DeleteModel(
            name="Asset",
        ),
    ]
