# Generated by Django 5.1.2 on 2025-05-20 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0018_alter_office_bank"),
        ("asset", "0004_assetcategory_remove_assetrecord_asset_and_more"),
        ("liability", "0013_liability_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assetitem",
            name="definition",
        ),
        migrations.RemoveField(
            model_name="assetrecord",
            name="definition",
        ),
        migrations.RemoveField(
            model_name="assetitem",
            name="seller",
        ),
        migrations.RemoveField(
            model_name="assetrecord",
            name="item",
        ),
        migrations.AlterModelOptions(
            name="assetrecord",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Asset Record",
                "verbose_name_plural": "Asset Records",
            },
        ),
        migrations.RenameField(
            model_name="assetrecord",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="assetrecord",
            old_name="note",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="assetrecord",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="assetrecord",
            name="payment_date",
            field=models.DateField(
                blank=True, help_text="Date of the transaction", null=True
            ),
        ),
        migrations.AddField(
            model_name="assetrecord",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_records",
                to="administration.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="assetrecord",
            name="quantity",
            field=models.IntegerField(
                help_text="Positive for additions, negative for consumption (inventory only)"
            ),
        ),
        migrations.AlterField(
            model_name="assetrecord",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("Addition", "Addition"),
                    ("Removal", "Removal"),
                    ("Sale", "Sale"),
                    ("Depreciation", "Depreciation"),
                ],
                default="Addition",
                help_text="Type of transaction (addition, removal, sale)",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "capitalization_date",
                    models.DateField(help_text="Date when the asset was capitalized"),
                ),
                (
                    "depreciation_start",
                    models.DateField(
                        help_text="When depreciation begins; defaults to capitalization date"
                    ),
                ),
                (
                    "useful_life_years",
                    models.PositiveIntegerField(
                        help_text="Expected useful life in years"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_service", "In Service"),
                            ("disposed", "Disposed"),
                            ("under_repair", "Under Repair"),
                        ],
                        default="in_service",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category of the fixed asset",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_assets",
                        to="asset.assetcategory",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        help_text="The seller of the fixed asset",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sold_fixed_assets",
                        to="liability.liability",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fixed Asset",
                "verbose_name_plural": "Fixed Assets",
            },
        ),
        migrations.AddField(
            model_name="assetrecord",
            name="fixed_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="asset.fixedasset",
            ),
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "inventory_type",
                    models.CharField(
                        choices=[
                            ("stock", "Stock Item"),
                            ("ledger", "Cost of Sales Ledger Item"),
                        ],
                        default="stock",
                        help_text="Determines behavior and related attributes",
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="administration.office",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        help_text="The seller of the inventory item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sold_inventory",
                        to="liability.liability",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "ordering": ["name"],
                "unique_together": {("name", "seller")},
            },
        ),
        migrations.AddField(
            model_name="assetrecord",
            name="inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="asset.inventory",
            ),
        ),
        migrations.DeleteModel(
            name="AssetDefinition",
        ),
        migrations.DeleteModel(
            name="AssetItem",
        ),
    ]
