# Generated by Django 5.1 on 2024-09-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_balance_alter_expensepayment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensepayment',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
