# Generated by Django 5.1.2 on 2024-10-23 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_bankpayment_created_by_bankpayment_transaction'),
        ('expenses', '0007_remove_expense_approved_expensepayment_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensepayment',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank'),
        ),
    ]
