# Generated by Django 5.1.2 on 2024-11-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_expensepaymentbatch_expensepaymentbatchitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensepaymentbatchitem',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='expensepaymentbatch',
            name='payment_date',
            field=models.DateField(default='2024-11-21'),
            preserve_default=False,
        ),
    ]
