# Generated by Django 5.1.2 on 2024-11-30 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_monthstatus'),
        ('expenses', '0010_remove_expensepaymentbatchitem_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensepayment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_payments', to='administration.transaction'),
        ),
        migrations.AlterField(
            model_name='expensepaymentbatch',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_payment_batches', to='administration.transaction'),
        ),
    ]
