# Generated by Django 5.1.2 on 2025-01-30 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_alter_tickets_repayment_schedule'),
        ('expenses', '0013_alter_expensepayment_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensepaymentbatch',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_payment_batches', to='administration.transaction'),
        ),
    ]
