# Generated by Django 5.1.2 on 2024-10-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='type',
            field=models.CharField(choices=[('Expenses', 'expenses'), ('Loan', 'loan'), ('Withdrawal', 'withdrawal')], max_length=100),
        ),
    ]
