# Generated by Django 5.1.2 on 2024-10-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_salary_absent_days_salary_absent_deductions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='prorated_days',
            field=models.IntegerField(default=0),
        ),
    ]
