# Generated by Django 5.1.2 on 2024-10-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_salary_prorated_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='prorated_days_deductions',
            new_name='prorated_days_deduction',
        ),
    ]
