# Generated by Django 5.1.2 on 2024-10-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_rename_prorated_days_deductions_salary_prorated_days_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='attendance_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
