# Generated by Django 5.1.2 on 2024-11-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_approval_type_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='type',
            field=models.CharField(choices=[('Expenses', 'expenses'), ('Batch_Expense', 'batch_expense'), ('Loan', 'loan'), ('Withdrawal', 'withdrawal'), ('Salary', 'salary')], max_length=100),
        ),
    ]
