# Generated by Django 5.1.2 on 2024-11-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_alter_approval_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('month', 'year')},
            },
        ),
    ]
