# Generated by Django 5.1.2 on 2025-01-28 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_tickets_ticketupdates'),
        ('loan', '0015_alter_loan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='repayment_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='loan.loanrepaymentschedule'),
        ),
    ]
