# Generated by Django 5.1.2 on 2025-01-29 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_tickets_repayment_schedule'),
        ('loan', '0015_alter_loan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='repayment_schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='loan.loanrepaymentschedule'),
        ),
    ]
