# Generated by Django 5.1.2 on 2025-04-29 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0016_office"),
        ("bank", "0017_bank_created_by_bank_office_bank_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office",
            name="bank",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branch",
                to="bank.bank",
            ),
        ),
    ]
