apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: samadeolu7/krystar:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "phoenix.settings"
        - name: SERVICE_URI
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: SERVICE_URI
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: SECRET_KEY
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DB_PASSWORD
        - name: DB_SSLMODE
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DB_SSLMODE
        - name: DB_SSLROOTCERT
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DB_SSLROOTCERT
        - name: PRODUCTION
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: PRODUCTION
        - name: SMS_API_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: SMS_API_KEY
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: REDIS_URL