# Generated by Django 5.1.2 on 2025-01-10 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_journalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearEndEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_loans', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_end_entries', to='main.year')),
            ],
        ),
    ]
