# Generated by Django 5.1.2 on 2025-01-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_yearendentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearendentry',
            name='retained_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
