# Generated by Django 5.1.2 on 2025-02-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_yearendentry_retained_earnings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['-year']},
        ),
        migrations.AlterModelOptions(
            name='yearendentry',
            options={'ordering': ['-year']},
        ),
    ]
