# Generated by Django 5.1.2 on 2025-02-15 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0008_alter_client_client_id_alter_client_name"),
        ("main", "0008_alter_year_options_alter_yearendentry_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientgroup",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_groups",
                to="client.client",
            ),
        ),
        migrations.AddField(
            model_name="clientgroup",
            name="meeting_day",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
